project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!data/"
  resources:
    - "imgs/"
    - "slides/"
    - "data/"
    

website:
  title: "Teaching Demo @ UoE Psychology"
  navbar:
    background: light
    left:
      - text: Presentation
        href: slides/demo.html
      - text: Analyses
        href: slides/demo.html
      - text: Data
        href: slides/demo.html
  page-navigation: true


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

callout-icon: false


