project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!data/"
  resources:
    - "imgs/"
    - "slides/"
    - "data/"
    - "pages/"
    

website:
  title: "Teaching Demo @ UoE Psychology"
  navbar:
    background: light
    left:
      - text: Presentation slides
        href: slides/demo.html
      - text: Activity handout
        href: pages/activity-handout.pdf
      - text: Presentation handout
        href: pages/demo-handout-formatted.pdf
      - text: Detailed analyses
        href: pages/detailed-analyses.html
  page-navigation: true


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

callout-icon: false


